### ISSUE TITLE
Can't login with default user or custom

### ISSUE THREAD

**Issue by glats** [bitnami/bitnami-docker-sonarqube#2] opened 2018-12-11 16:38 UTC
**Description**
Can't login into the app

**Steps to reproduce the issue:**

1. Create the docker-compose.ml
2. run ```docker-compose up```
3. Trying to login

**Describe the results you received:**
Error while im trying to login. A 401 error code appear after hit the button

**Describe the results you expected:**

Login and use the web appp

**Additional information you deem important (e.g. issue happens only occasionally):**

```
version: "3.5"
services:
  postgresql:
    image: bitnami/postgresql:10
    volumes:
      - 'postgresql_data:/bitnami'
  sonarqube:
    image: bitnami/sonarqube:latest
    ports:
      - '9000:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_USERNAME=admin
      - SONARQUBE_PASSWORD=admin
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local
```
I put SONARQUBE_USERNAME and SONARQUBE_PASSWORD by my own and still didnt work.

![captura de pantalla de 2018-12-11 13-34-53](https://user-images.githubusercontent.com/4707766/49815122-d3a44c00-fd49-11e8-9cc2-5d316e01f5f8.png)
![captura de pantalla de 2018-12-11 13-35-14](https://user-images.githubusercontent.com/4707766/49815124-d4d57900-fd49-11e8-803a-3b20e92ccabf.png)

## Did i miss something?

**Version**

- Output of `docker version`:

```
$ docker version
Client:
 Version:           18.09.0-ce
 API version:       1.39
 Go version:        go1.11.2
 Git commit:        4d60db472b
 Built:             Fri Nov  9 00:05:34 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.0-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.2
  Git commit:       4d60db472b
  Built:            Fri Nov  9 00:05:11 2018
  OS/Arch:          linux/amd64
  Experimental:     true
```

- Output of `docker info`:

```
$ docker info
Containers: 2
 Running: 2
 Paused: 0
 Stopped: 0
Images: 2
Server Version: 18.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: hj211cchfzkxru2gvpxioc1hy
 Is Manager: true
 ClusterID: qp95wjqewvez3gg3a1cz0n237
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 10
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.28.108.56
 Manager Addresses:
  172.28.108.56:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b.m
runc version: 079817cc26ec5292ac375bb9f47f373d33574949
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.19.4-arch1-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 15.56GiB
Name: arch-revenge
ID: DDCO:3CVD:WF44:XM35:J3IZ:3EQ2:O5GN:KEAA:KHJJ:43CP:CRIW:YPGA
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: http://proxy.vtr.cl:8080/
No Proxy: localhost,127.0.0.0/8,*.vtr.cl
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 172.17.236.15:8082
 172.17.236.15:8083
 127.0.0.0/8
Live Restore Enabled: false

```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.23.2, build unknown
docker-py version: 3.6.0
CPython version: 3.7.1
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by juan131** [comment] 2018-12-12 07:53
Hi @glats 

I was unable to reproduce the issue. I could login with my "custom credentials" using the `docker-compose.yaml` below:

```
version: '2'
services:
  postgresql:
    image: 'bitnami/postgresql:10'
    volumes:
      - postgresql_data:/bitnami
  sonarqube:
    image: bitnami/sonarqube:latest
    ports:
      - '9000:9000'
    environment:
      - POSTGRESQL_HOST=postgresql
      - POSTGRESQL_ROOT_USER=postgres
      - POSTGRESQL_CLIENT_CREATE_DATABASE_NAME=bitnami_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_USERNAME=bn_sonarqube
      - POSTGRESQL_CLIENT_CREATE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
      - SONARQUBE_DATABASE_USER=bn_sonarqube
      - SONARQUBE_DATABASE_PASSWORD=bitnami1234
      - SONARQUBE_USERNAME=admin
      - SONARQUBE_PASSWORD=admin1234
    volumes:
      - sonarqube_data:/bitnami
volumes:
  sonarqube_data:
    driver: local
  postgresql_data:
    driver: local
```

See the screenshot after login:

![screenshot 2018-12-12 at 08 51 09](https://user-images.githubusercontent.com/6740773/49854644-19fdb780-fdeb-11e8-9027-2a0a0ad1ceb7.png)

The only big difference between your YAML and mine is the docker-compose version.. Did you run `docker-compose up` without persisted data from previous deployments?

Command used:

```
docker-compose down -v
docker-compose up -d
```

**Comment by glats** [comment] 2018-12-12 15:31
Finally i made it work.
First i deleted my daemon.json file because it has a lot of custom configuration that provide me a good environment. Here it's my config just in case:
```
{
"bip":"192.168.1.5/24",
"experimental":true,
"default-address-pools":
[
 {"base":"10.10.0.0/16","size":24}
],
"storage-driver": "overlay2",
"insecure-registries": [
  "172.17.236.15:8082",
  "172.17.236.15:8083"
],
"disable-legacy-registry": true
}
``` 
Then I stopped the service runing ``` sudo systemctl stop docker``` and i removed everything in /var/lib/docker and started the service again. 
When i ran docker-compose up, works fine.
I don't know what or which field in daemon.json could be the problem with the login.

**Comment by juan131** [comment] 2018-12-12 15:42
Hi @glats 

I'm glad you could solve the issue!! I guess there was something on your network configuration that was causing the issue when accessing the site.

I'll proceed to close the issue as solved. Please do not hesitate to reopen it if you need further help.

**Closed by juan131** 2018-12-12 15:42 UTC
