### ISSUE TITLE
JDBC connection failure when using non-standard postgresql port

### ISSUE THREAD

**Issue by oetlinge** [bitnami/bitnami-docker-sonarqube#19] opened 2020-03-19 17:16 UTC
**Description**

Setting up bitnami dockerized SonarQube instance with docker compose and trying to target a remote Postgresql database listening on a port other than the default (5432).  I've confirmed the database credentials specified in the docker-compose.yml file are correct, but the web.log file in the SonarQube container suggests the POSTGRESQL_PORT_NUMBER variable is being ignored.

**Steps to reproduce the issue:**

1. Created docker-compose.yml file with definition for SonarQube as below:
```
    sonarqube:
        image: 'bitnami/sonarqube:8'
        ports:
          - '9000:9000'
        environment:
          - POSTGRESQL_HOST=3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud
          - POSTGRESQL_PORT_NUMBER=30408
          - SONARQUBE_DATABASE_NAME=bitnami_sonarqube
          - SONARQUBE_DATABASE_USER=<db_user>
          - SONARQUBE_DATABASE_PASSWORD=<db_password>
          - SONARQUBE_USERNAME=admin
          - SONARQUBE_PASSWORD=bitnami
          - SONARQUBE_START_TIMEOUT=600
          - NAMI_LOG_LEVEL=trace
        volumes:
          - sonarqube_data:/bitnami
```
2. Start container via docker-compose
3. Examine contents of docker container.

**Describe the results you received:**

Although sonarqube-inputs.json contains input mapping for database server port:
 `"databaseServerPort": "{{$global.env.POSTGRESQL_PORT_NUMBER}}"`

opt/bitnami/sonarqube/conf/sonar.properties specifies sonar.jdbc.url as:
`sonar.jdbc.url=jdbc:postgresql://3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf
10402584b5f01db462d330.databases.appdomain.cloud/bitnami_sonarqube` and there is no mention of the port number.

opt/bitnami/sonarqube/logs/web.log confirms the problem with jdbc url:
```
2020.03.19 14:07:21 INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud/bitnami_sonarqube
2020.03.19 14:07:31 ERROR web[][o.s.s.p.PlatformImpl] Web server startup failed
java.lang.IllegalStateException: Fail to connect to database
```

**Describe the results you expected:**

Specified port from POSTGRESQL_PORT_NUMBER should be applied to jdbc connection url.
**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:25:41 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:24:18 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 1
  Paused: 0
  Stopped: 1
 Images: 2
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-693.21.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.639GiB
 Name: sectestcoc
 ID: OZ3W:ISPV:SMSX:4Z7O:M3OM:HPBC:P5AC:E2CA:6GNW:33Z5:4WTM:O77M
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  bxv8v141.cn.ibm.com
  wcnexus.torolab.ibm.com
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.20.1, build 5d8c71b
docker-py version: 3.1.4
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by Mauraza** [comment] 2020-03-20 10:40
Hi @oetlinge,

could you try inside the container of sonarqube to connect the database with [psql](http://postgresguide.com/utilities/psql.html)? You can do something like:

```
docker exec -ti your-container-sonarqube psql -U db_user -h 3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud -p 30408 bitnami_sonarqube
```

**Comment by oetlinge** [comment] 2020-03-20 13:38
@Mauraza Using psql as you suggested above connects to the database successfully.

**Comment by Mauraza** [comment] 2020-03-23 11:37
Hi @oetlinge ,

Could you add the 'docker-compose logs'? please, I need more information because I can't reproduce the issue.

**Comment by oetlinge** [comment] 2020-03-23 16:49
```
Attaching to sonarqube_sonarqube_1
sonarqube_1  |
sonarqube_1  | Welcome to the Bitnami sonarqube container
sonarqube_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-sonarqube
sonarqube_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-sonarqube/issues
sonarqube_1  | Send us your feedback at containers@bitnami.com
sonarqube_1  |
sonarqube_1  | nami    INFO  Initializing postgresql-client
sonarqube_1  | nami    INFO  postgresql-client successfully initialized
sonarqube_1  | nami    INFO  Initializing sonarqube
sonarqube_1  | sonarqu DEBUG ==> Creating SonarQube System User...
sonarqube_1  | sonarqu INFO  ==> Creating server folders...
sonarqube_1  | sonarqu INFO  ==> Configuring database parameters...
sonarqube_1  | sonarqu INFO  ==> Configuring server parameters...
sonarqube_1  | sonarqu INFO  ==> Configure permissions...
sonarqube_1  | sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/data
sonarqube_1  | sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/temp
sonarqube_1  | sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/logs
sonarqube_1  | sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/extensions
sonarqube_1  | sonarqu TRACE [configurePermissions] File to chown: /opt/bitnami/sonarqube/pids
sonarqube_1  | sonarqu INFO  ==> Initializing SonarQube from scratch...
sonarqube_1  | postgre INFO  Trying to connect to PostgreSQL server
sonarqube_1  | postgre INFO  Found PostgreSQL server listening at 3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:30408
sonarqube_1  | postgre TRACE [canConnect] Testing connection with 'ibm_cloud_4deeaf0e_e5a0_4c2f_a1e8_accef9f287f2' user
sonarqube_1  | postgre TRACE [showDatabases] Getting databases for 'ibm_cloud_4deeaf0e_e5a0_4c2f_a1e8_accef9f287f2' user
sonarqube_1  | postgre TRACE [execute] Executing psql with parameters -t,-p30408,-h3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud,-dbitnami_sonarqube,-Uibm_cloud_4deeaf0e_e5a0_4c2f_a1e8_accef9f287f2,-cSELECT datname FROM pg_database;
sonarqube_1  | postgre TRACE [showDatabases] Databases: " postgres\n ibmclouddb\n template0\n template1\n bitnami_sonarqube\n\n"
sonarqube_1  | postgre TRACE [canConnect] Connection with 'ibm_cloud_4deeaf0e_e5a0_4c2f_a1e8_accef9f287f2' user is successful
sonarqube_1  | postgre INFO  PostgreSQL server listening and working at 3f8f022e-c61a-45f0-949f-fa35cda9cd10.bc28ac43cf10402584b5f01db462d330.databases.appdomain.cloud:30408
sonarqube_1  | sonarqu INFO  ==> Starting app...
sonarqube_1  | sonarqu TRACE [runProgram] Executing: null su - sonarqube -c 'PATH=/opt/bitnami/java/bin:/opt/bitnami/postgresql/bin:/opt/bitnami/java/bin:/opt/bitnami/sonarqube/bin/linux-x86-64/:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin /opt/bitnami/sonarqube/bin/linux-x86-64/sonar.sh start'
sonarqube_1  | sonarqu TRACE code: 0
sonarqube_1  | sonarqu TRACE stdout:
sonarqube_1  |
sonarqube_1  | sonarqu TRACE stderr:
sonarqube_1  |
sonarqube_1  | sonarqu ERROR Pattern SonarQube is up was not found in SonarQube log: Error: Log entry not found after 600 s.
sonarqube_1  | Error executing 'postInstallation': Log entry not found after 600 s.
sonarqube_1  | nami    TRACE Error: Error executing 'postInstallation': Log entry not found after 600 s.
sonarqube_1  |     at Object.waitForEntry (/root/.nami/components/com.bitnami.sonarqube/lib/log.js:33:41)
sonarqube_1  |     at Object.$app.helpers.waitForLogEntry (/root/.nami/components/com.bitnami.sonarqube/helpers.js:92:18)
sonarqube_1  |     at Service.$app.postInstallation (/root/.nami/components/com.bitnami.sonarqube/main.js:62:18)
sonarqube_1  |     at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
sonarqube_1  |     at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
sonarqube_1  |     at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
sonarqube_1  |     at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
sonarqube_1  |     at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
sonarqube_1  |     at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)
sonarqube_1  |     at Command.cmdOpts.callback (/opt/bitnami/nami/cli/nami-app.js:331:24)
sonarqube_sonarqube_1 exited with code 1
```

**Comment by Mauraza** [comment] 2020-03-23 17:28
Hello @oetlinge,

I investigated and it looks like this error was for the host. Could you try to run:
`sysctl -w vm.max_map_count=262144`

**Comment by oetlinge** [comment] 2020-03-23 17:46
@Mauraza My setting for `vm.max_map_count` was already at 262144 when I tried starting the container, so I don't think that's the cause of the problem.

**Comment by Mauraza** [comment] 2020-03-24 11:56
Hi @oetlinge,

We will investigate more about what it's happened. When we fixed I update this thread with more news. 

Thanks for reporting!

**Comment by beltran-rubo** [comment] 2020-03-26 07:34
Just a note to let you know this issue has been fixed in the latest image available "8.2.0-debian-10-r11". Please, make sure you specify that tag or remove the existing image in your machine to be downloaded again the latest version. 

Please confirm that version fixed the issue.

**Comment by oetlinge** [comment] 2020-04-13 00:17
Thanks. Will confirm fix tomorrow.

**Comment by oetlinge** [comment] 2020-04-13 15:33
Port number from POSTGRESQL_PORT_NUMBER is now correctly applied to JDBC connection URL. Thanks for fixing this issue.

**Comment by beltran-rubo** [comment] 2020-04-13 15:41
thanks for confirm it!

**Closed by beltran-rubo** 2020-04-13 15:41 UTC
